"""movie data tables

Revision ID: 5544a24bfc95
Revises: 
Create Date: 2019-09-15 15:24:26.422301

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5544a24bfc95'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('actor',
    sa.Column('actor_name', sa.String(length=64), nullable=False),
    sa.Column('movie_name', sa.String(length=64), nullable=True),
    sa.Column('facebook_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_name'], ['movie.movie_name'], ),
    sa.PrimaryKeyConstraint('actor_name'),
    sa.UniqueConstraint('movie_name')
    )
    op.create_table('director',
    sa.Column('director_name', sa.String(length=64), nullable=False),
    sa.Column('movie_name', sa.String(length=64), nullable=True),
    sa.Column('facebook_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['movie_name'], ['movie.movie_name'], ),
    sa.PrimaryKeyConstraint('director_name'),
    sa.UniqueConstraint('movie_name')
    )
    op.create_table('movie',
    sa.Column('movie_name', sa.String(length=64), nullable=False),
    sa.Column('actor_name', sa.String(length=64), nullable=True),
    sa.Column('director_name', sa.String(length=64), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=True),
    sa.Column('facebook_likes', sa.Integer(), nullable=True),
    sa.Column('num_critic_for_reviews', sa.Integer(), nullable=True),
    sa.Column('duration', sa.Integer(), nullable=True),
    sa.Column('gross', sa.Integer(), nullable=True),
    sa.Column('genres', sa.String(length=64), nullable=True),
    sa.Column('num_voted_users', sa.Integer(), nullable=True),
    sa.Column('cast_total_facebook_likes', sa.Integer(), nullable=True),
    sa.Column('facenumber_in_poster', sa.Integer(), nullable=True),
    sa.Column('plot_keywords', sa.String(length=64), nullable=True),
    sa.Column('movie_imdb_link', sa.String(length=64), nullable=True),
    sa.Column('num_user_for_reviews', sa.String(length=64), nullable=True),
    sa.Column('language', sa.String(length=64), nullable=True),
    sa.Column('country', sa.String(length=64), nullable=True),
    sa.Column('content_rating', sa.String(length=64), nullable=True),
    sa.Column('budget', sa.Integer(), nullable=True),
    sa.Column('title_year', sa.Integer(), nullable=True),
    sa.Column('imdb_score', sa.Float(), nullable=True),
    sa.Column('aspect_ratio', sa.Float(), nullable=True),
    sa.Column('movie_facebook_likes', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['actor_name'], ['actor.actor_name'], ),
    sa.ForeignKeyConstraint(['director_name'], ['director.director_name'], ),
    sa.PrimaryKeyConstraint('movie_name'),
    sa.UniqueConstraint('actor_name'),
    sa.UniqueConstraint('director_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('movie')
    op.drop_table('director')
    op.drop_table('actor')
    # ### end Alembic commands ###
